### ISSUE TITLE
Unable to download skullbreak data

### ISSUE THREAD

**Issue by sam-zyzhang** [pfriedri/pcdiff-implant#2]
Hello, Thank you for sharing your work and code!

I want to download the Skullbreak dataset via the link to train the network, but the website indicates that I do not have permission to view the webpage containing the data. Could you please reshare the link to the skullbreak dataset?

**Comment by pfriedri** [comment]
@sam-zyzhang Thank you for your interest in our work.

This is the link provided in the "SkullBreak/SkullFix - Dataset for automatic cranial implant design and a benchmark for volumetric shape learning tasks" paper by Kodym et al., but you are right, it is also not working for us anymore.

Since this is not our dataset or website, I would suggest contacting the authors.
